name: ultima
description: Ultima an arcore and arkit contribution ar makeup-tryon application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  responsive_sizer: ^3.1.1
  google_fonts: ^4.0.3
  eva_icons_flutter: ^3.1.0
  steps_indicator: ^1.3.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.2.0
  flutter_switch: ^0.3.2
  page_transition: ^2.0.9
  carousel_slider: ^4.2.1
  mrx_charts: ^0.1.3
  fl_chart: ^0.60.0
  tab_indicator_styler: ^2.0.0
  firebase_core: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/
