// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChjM6At47DmEllhl028Vd4u-xeFcPd5UY',
    appId: '1:889329332221:android:2a7ea79248d6244ba7f394',
    messagingSenderId: '889329332221',
    projectId: 'ultima-b32f3',
    storageBucket: 'ultima-b32f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgCRaQUR5A2dMzHVSWZ6zzMgMPHUfiiDU',
    appId: '1:889329332221:ios:367868b305f8e16ea7f394',
    messagingSenderId: '889329332221',
    projectId: 'ultima-b32f3',
    storageBucket: 'ultima-b32f3.appspot.com',
    androidClientId: '889329332221-4td8jbhebo5qkrcea6t4quavv31r9p1g.apps.googleusercontent.com',
    iosClientId: '889329332221-1g6dq92pkpunq67khssccvrb9060g532.apps.googleusercontent.com',
    iosBundleId: 'com.ultima.ultima',
  );
}
